function value = adc(numSamples, dwellSeconds, options)
%ADC Construct an LBTX ADC event.
arguments
    numSamples (1, 1) double {mustBeInteger, mustBePositive}
    dwellSeconds (1, 1) double {mustBePositive}
    options.DelaySeconds (1, 1) double {mustBeNonnegative} = 0
    options.FrequencyOffsetHz (1, 1) double {mustBeFinite} = 0
    options.PhaseOffsetRad (1, 1) double {mustBeFinite} = 0
    options.FrequencyOffsetPpm (1, 1) double {mustBeFinite} = 0
    options.PhaseOffsetPpm (1, 1) double {mustBeFinite} = 0
    options.DeadTimeSeconds (1, 1) double {mustBeNonnegative} = 0
    options.PhaseModulationRad (1, :) double {mustBeFinite} = []
end
if ~isempty(options.PhaseModulationRad) && numel(options.PhaseModulationRad) ~= numSamples
    error("seqcraft:InvalidADC", "PhaseModulationRad must be empty or contain numSamples values.");
end
payload = struct( ...
    "num_samples", numSamples, ...
    "dwell_s", seqcraft.decimal(dwellSeconds), ...
    "delay_s", seqcraft.decimal(options.DelaySeconds), ...
    "frequency_offset_hz", options.FrequencyOffsetHz, ...
    "phase_offset_rad", options.PhaseOffsetRad, ...
    "frequency_offset_ppm", options.FrequencyOffsetPpm, ...
    "phase_offset_ppm", options.PhaseOffsetPpm, ...
    "dead_time_s", seqcraft.decimal(options.DeadTimeSeconds), ...
    "phase_modulation_rad", options.PhaseModulationRad);
value = seqcraft.event("adc", payload);
end
