function value = scannerOpts(maxGradHzPerM, maxSlewHzPerMPerS, options)
%SCANNEROPTS Construct the explicit canonical scanner-options payload for LBTX.
arguments
    maxGradHzPerM (1, 1) double {mustBePositive}
    maxSlewHzPerMPerS (1, 1) double {mustBePositive}
    options.MaxB1Hz (1, 1) double {mustBeNonnegative} = 0
    options.MaxFrequencyOffsetHz (1, 1) double {mustBeNonnegative} = 250000
    options.RFDeadTimeSeconds (1, 1) double {mustBeNonnegative} = 0
    options.RFRingdownTimeSeconds (1, 1) double {mustBeNonnegative} = 0
    options.ADCDeadTimeSeconds (1, 1) double {mustBeNonnegative} = 0
    options.ADCRasterTimeSeconds (1, 1) double {mustBePositive} = 1e-7
    options.RFRasterTimeSeconds (1, 1) double {mustBePositive} = 1e-6
    options.GradientRasterTimeSeconds (1, 1) double {mustBePositive} = 1e-5
    options.BlockDurationRasterSeconds (1, 1) double {mustBePositive} = 1e-5
    options.ADCSamplesLimit (1, 1) double {mustBeInteger, mustBeNonnegative} = 0
    options.RFSamplesLimit (1, 1) double {mustBeInteger, mustBeNonnegative} = 0
    options.ADCSamplesDivisor (1, 1) double {mustBeInteger, mustBePositive} = 4
    options.TriggerIdentifierSupported (1, 1) logical = true
    options.GammaHzPerT (1, 1) double {mustBePositive} = 42576000
    options.B0T (1, 1) double {mustBeNonnegative} = 1.5
end
value = struct( ...
    "max_b1_hz", options.MaxB1Hz, ...
    "max_grad_hz_per_m", maxGradHzPerM, ...
    "max_slew_hz_per_m_per_s", maxSlewHzPerMPerS, ...
    "max_frequency_offset_hz", options.MaxFrequencyOffsetHz, ...
    "rf_dead_time_s", seqcraft.decimal(options.RFDeadTimeSeconds), ...
    "rf_ringdown_time_s", seqcraft.decimal(options.RFRingdownTimeSeconds), ...
    "adc_dead_time_s", seqcraft.decimal(options.ADCDeadTimeSeconds), ...
    "adc_raster_time_s", seqcraft.decimal(options.ADCRasterTimeSeconds), ...
    "rf_raster_time_s", seqcraft.decimal(options.RFRasterTimeSeconds), ...
    "grad_raster_time_s", seqcraft.decimal(options.GradientRasterTimeSeconds), ...
    "block_duration_raster_s", seqcraft.decimal(options.BlockDurationRasterSeconds), ...
    "adc_samples_limit", options.ADCSamplesLimit, ...
    "rf_samples_limit", options.RFSamplesLimit, ...
    "adc_samples_divisor", options.ADCSamplesDivisor, ...
    "trigger_identifier_supported", options.TriggerIdentifierSupported, ...
    "gamma_hz_per_t", options.GammaHzPerT, ...
    "b0_t", options.B0T);
end
