% GRE_2D_MODULE Build the same small GRE 2D scan through a SeqCraft Module.

if ~exist("outputPath", "var") || strlength(string(outputPath)) == 0
    outputPath = fullfile(tempdir, "seqcraft_gre_2d_module.seq");
end
if ~exist("pythonExecutable", "var")
    pythonExecutable = "";
end

matrix = [16 8];
fovM = [0.22 0.22];
sliceThicknessM = 5e-3;

opts = mr.opts( ...
    "MaxGrad", 40, "GradUnit", "mT/m", ...
    "MaxSlew", 150, "SlewUnit", "T/m/s", ...
    "rfDeadTime", 100e-6, ...
    "rfRingdownTime", 30e-6, ...
    "adcDeadTime", 10e-6, ...
    "B0", 3);

gre = seqcraft_examples.GRE2D( ...
    opts, ...
    Matrix=matrix, ...
    FOVM=fovM, ...
    SliceThicknessM=sliceThicknessM, ...
    FlipAngleRad=deg2rad(10), ...
    TRSeconds=20e-3, ...
    DwellSeconds=20e-6);
root = gre.build();

definitions = struct("FOV", [fovM sliceThicknessM], "Matrix", matrix);
seq = seqcraft.compile( ...
    root, opts, string(outputPath), ...
    Definitions=definitions, ...
    PythonExecutable=string(pythonExecutable));
[timingOk, timingReport] = seq.checkTiming();
assert(timingOk, strjoin(timingReport, newline));

fprintf("Wrote %s\n", string(outputPath));
