% GRE_2D_LOGICBLOCK Build a small GRE 2D scan directly from native Pulseq events.

if ~exist("outputPath", "var") || strlength(string(outputPath)) == 0
    outputPath = fullfile(tempdir, "seqcraft_gre_2d_logicblock.seq");
end
if ~exist("pythonExecutable", "var")
    pythonExecutable = "";
end

matrix = [16 8];
fovM = [0.22 0.22];
sliceThicknessM = 5e-3;
flipAngleRad = deg2rad(10);
trSeconds = 20e-3;
dwellSeconds = 20e-6;

opts = mr.opts( ...
    "MaxGrad", 40, "GradUnit", "mT/m", ...
    "MaxSlew", 150, "SlewUnit", "T/m/s", ...
    "rfDeadTime", 100e-6, ...
    "rfRingdownTime", 30e-6, ...
    "adcDeadTime", 10e-6, ...
    "B0", 3);

% Design native Pulseq events once.
[rf, gz, gzRephaseMinimum] = mr.makeSincPulse( ...
    flipAngleRad, opts, ...
    "Duration", 1e-3, ...
    "SliceThickness", sliceThicknessM, ...
    "use", "excitation");

readoutArea = matrix(1) / fovM(1);
gx = mr.makeTrapezoid( ...
    "x", opts, "FlatArea", readoutArea, "FlatTime", matrix(1) * dwellSeconds);
adc = mr.makeAdc( ...
    matrix(1), opts, "Dwell", dwellSeconds, "Delay", gx.riseTime);

winderMaxGrad = opts.maxGrad / sqrt(3);
winderMaxSlew = opts.maxSlew / sqrt(3);
gzRephaseConstrainedMinimum = mr.makeTrapezoid( ...
    "z", opts, "Area", gzRephaseMinimum.area, ...
    "maxGrad", winderMaxGrad, "maxSlew", winderMaxSlew);
gxPreMinimum = mr.makeTrapezoid( ...
    "x", opts, "Area", -gx.area / 2, ...
    "maxGrad", winderMaxGrad, "maxSlew", winderMaxSlew);
centerLine = floor(matrix(2) / 2);
gyMaximum = mr.makeTrapezoid( ...
    "y", opts, "Area", centerLine / fovM(2), ...
    "maxGrad", winderMaxGrad, "maxSlew", winderMaxSlew);
winderSeconds = max([ ...
    mr.calcDuration(gzRephaseConstrainedMinimum), ...
    mr.calcDuration(gxPreMinimum), ...
    mr.calcDuration(gyMaximum)]);
winderSeconds = ceil(winderSeconds / opts.gradRasterTime) * opts.gradRasterTime;

gzRephase = mr.makeTrapezoid( ...
    "z", opts, "Area", gzRephaseMinimum.area, "Duration", winderSeconds, ...
    "maxGrad", winderMaxGrad, "maxSlew", winderMaxSlew);
gxPre = mr.makeTrapezoid( ...
    "x", opts, "Area", -gx.area / 2, "Duration", winderSeconds, ...
    "maxGrad", winderMaxGrad, "maxSlew", winderMaxSlew);
phaseEncodes = cell(1, matrix(2));
lineLabels = cell(1, matrix(2));
for lineIndex = 0:(matrix(2) - 1)
    phaseEncodes{lineIndex + 1} = mr.makeTrapezoid( ...
        "y", opts, ...
        "Area", (lineIndex - centerLine) / fovM(2), ...
        "Duration", winderSeconds, ...
        "maxGrad", winderMaxGrad, "maxSlew", winderMaxSlew);
    lineLabels{lineIndex + 1} = mr.makeLabel("SET", "LIN", lineIndex);
end

spoilMaxGrad = opts.maxGrad / sqrt(2);
spoilMaxSlew = opts.maxSlew / sqrt(2);
gxSpoilMinimum = mr.makeTrapezoid( ...
    "x", opts, "Area", 2 * readoutArea, ...
    "maxGrad", spoilMaxGrad, "maxSlew", spoilMaxSlew);
gzSpoilMinimum = mr.makeTrapezoid( ...
    "z", opts, "Area", 2 / sliceThicknessM, ...
    "maxGrad", spoilMaxGrad, "maxSlew", spoilMaxSlew);
spoilSeconds = max(mr.calcDuration(gxSpoilMinimum), mr.calcDuration(gzSpoilMinimum));
gxSpoil = mr.makeTrapezoid( ...
    "x", opts, "Area", 2 * readoutArea, "Duration", spoilSeconds, ...
    "maxGrad", spoilMaxGrad, "maxSlew", spoilMaxSlew);
gzSpoil = mr.makeTrapezoid( ...
    "z", opts, "Area", 2 / sliceThicknessM, "Duration", spoilSeconds, ...
    "maxGrad", spoilMaxGrad, "maxSlew", spoilMaxSlew);

excitationSeconds = mr.calcDuration(rf, gz);
readoutSeconds = mr.calcDuration(gx, adc);
readoutStart = excitationSeconds + winderSeconds;
spoilStart = readoutStart + readoutSeconds;
contentSeconds = spoilStart + spoilSeconds;
assert(contentSeconds < trSeconds, "GRE line does not fit in the requested TR.");
trDelay = mr.makeDelay(trSeconds - contentSeconds);

% Assemble the tree without a Module.
root = seqcraft.LogicBlock("gre_2d");
for lineIndex = 0:(matrix(2) - 1)
    line = seqcraft.LogicBlock("line_" + lineIndex);
    line.add(0, rf, gz);
    line.add(excitationSeconds, gzRephase, gxPre, phaseEncodes{lineIndex + 1});
    line.add(readoutStart, gx, adc, lineLabels{lineIndex + 1});
    line.add(spoilStart, gxSpoil, gzSpoil);
    line.add(contentSeconds, trDelay);
    root.add(lineIndex * trSeconds, line);
end

definitions = struct("FOV", [fovM sliceThicknessM], "Matrix", matrix);
seq = seqcraft.compile( ...
    root, opts, string(outputPath), ...
    Definitions=definitions, ...
    PythonExecutable=string(pythonExecutable));
[timingOk, timingReport] = seq.checkTiming();
assert(timingOk, strjoin(timingReport, newline));

fprintf("Wrote %s\n", string(outputPath));
